// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSADSEyGxbSh_8ZNU3AKPs-vCVAGhOf1I',
    appId: '1:479627633708:web:5044a284aba986bd3c1d89',
    messagingSenderId: '479627633708',
    projectId: 'stylecutz-app',
    authDomain: 'stylecutz-app.firebaseapp.com',
    storageBucket: 'stylecutz-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa_G6Fzg0TmJE6vRPVJtQQ2CF1PGQg1oU',
    appId: '1:479627633708:android:ae7035bacc82c2193c1d89',
    messagingSenderId: '479627633708',
    projectId: 'stylecutz-app',
    storageBucket: 'stylecutz-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpCPgWJkb9-ekZZHDdNtvfAfb5ikSJl9w',
    appId: '1:479627633708:ios:4e6d3392f24c69bd3c1d89',
    messagingSenderId: '479627633708',
    projectId: 'stylecutz-app',
    storageBucket: 'stylecutz-app.firebasestorage.app',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpCPgWJkb9-ekZZHDdNtvfAfb5ikSJl9w',
    appId: '1:479627633708:ios:4e6d3392f24c69bd3c1d89',
    messagingSenderId: '479627633708',
    projectId: 'stylecutz-app',
    storageBucket: 'stylecutz-app.firebasestorage.app',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSADSEyGxbSh_8ZNU3AKPs-vCVAGhOf1I',
    appId: '1:479627633708:web:9b18104422518f543c1d89',
    messagingSenderId: '479627633708',
    projectId: 'stylecutz-app',
    authDomain: 'stylecutz-app.firebaseapp.com',
    storageBucket: 'stylecutz-app.firebasestorage.app',
  );
}
